[package]
name = "matmul"
version = "0.1.0"
edition = "2024"

[dependencies]
cust = { path = "../../../crates/cust" }
cuda_std = { path = "../../../crates/cuda_std" }

[build-dependencies]
cuda_builder = { workspace = true, default-features = false }